### ISSUE TITLE
Broker does not start when database is empty

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#126]
After cleaning all databases and doing a fresh start of the Broker version `registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/core:5.0.2` and `registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/fuseki:5.0.2` I'm getting the following broker log:

```
23-11-2022 08:28:41.576 [main] INFO  de.fraunhofer.iais.eis.ids.index.common.persistence.RepositoryFacade.getNewReadOnlyConnectionToFuseki - retry to establish connection to Fuseki server in 5 seconds
 23-11-2022 08:28:46.586 [main] INFO  de.fraunhofer.iais.eis.ids.index.common.persistence.RepositoryFacade.getNewReadOnlyConnectionToFuseki - unable to establish a connection to Fuseki server with url http://mobids-fuseki:3030/connectorData/sparql
 23-11-2022 08:28:46.587 [main] INFO  de.fraunhofer.iais.eis.ids.index.common.persistence.RepositoryFacade.getNewReadOnlyConnectionToFuseki - stop trying to establish connection and throw exception ... 
Nov 23, 2022 8:28:46 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Tomcat]
 08:28:46.623 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'main': Invocation of init method failed; nested exception is HttpException: 404 Not Found
```
Obviously the Broker cannot connect to the fuseki with resource or schema connectorData

**Comment by timwirtz86** [comment]
@sebplorenz can you please provide us with a reproducible setup? In the best-case use this [Postman collection](https://github.com/Mobility-Data-Space/MDS-Broker-Core/blob/main/doc/IDS%20Broker%20ES%20Tests%20with%20MDS.postman_collection.json)

**Comment by sebplorenz** [comment]
I cannot use a Postman Collection since the Broker, that this collection is talking to, is not starting up!

This is my setup. It was working without problems as long as there was content in the database. Now, after cleaning the database, it is not starting up anymore:

```
version: '2'
services:

  broker-core:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/core:5.0.1-MDS
    restart: always
    volumes:
      - /app/broker/cert:/etc/cert
    environment:
      - SPARQL_ENDPOINT=http://mobids-fuseki:3030/connectorData
      - SPARQL_URL=http://mobids-fuseki:3030/connectorData
      - ELASTICSEARCH_HOSTNAME=mobids-elasticsearch
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=true
      - COMPONENT_URI=https://broker.mobilitydataspace.io
      - COMPONENT_CATALOGURI=https://broker.mobilitydataspace.io/connectors/
      - SSL_JAVAKEYSTORE=/etc/cert/ids.broker.mobilitydataspace.io.p12
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - back-end:backend

  mobids-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/fuseki:5.0.2
    restart: always
    volumes:
      - broker_mobids-fuseki:/fuseki
    expose:
      - "3030"
    ports:
      - "3030:3030"

  mobids-elasticsearch:
    image: elasticsearch:7.16.2
    restart: always
    environment:
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=https://catalog.mobilitydataspace.io #Change the Value
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - discovery.type=single-node
    volumes:
      - broker_mobids-esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"

  mobids-searchfrontend:
#    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/frontend-mobids:5.0.1
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/frontend:5.0.1
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      - "REACT_APP_BROKER_URL=https://catalog.mobilitydataspace.io" #Change the Value

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - broker_db:/data/db

  back-end:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/mongodb-handler:4.2.7
    restart: always
    expose:
      - "4000"
    ports:
      - "4000:4000"
    environment:
      - MONGODB_ENDPOINT=mongodb://mongodb:27017/users
      - JWT_SECRET=anewstring
      - ADMIN_PASSWORD=admin_ids@broker123
      - BROKER_URL=http://broker-core:8080
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    links:
      - mongodb:mongo

volumes:
  broker_mobids-fuseki:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/broker/db/fuseki
  broker_mobids-esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/broker/db/esdata
  broker_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app/broker/db/broker
```
