### ISSUE TITLE
Broker not authenticated with local DAPS

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/metadata-broker-open-core#88]
I have deployed an omejdnDAPS, a DSC version 7.0.1 and the latest version of the metadata broker in my local environment.
The issue is that the broker is not authenticating our local DAPS.
With a previous release of the metadata broker, in order to set-up it we used the command "mvn clean package"  to create a broker-core-4.2.8-SNAPSHOT.jar with the correct files configured (broker-core/src/main/resources/isstbroker-keystore.jks and application.properties with daps.url specified). 

Currently, the "mvn clean package" is not working with the latest version of the metadata broker. I used this in order to create our "registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/core" image.

Now, with the docker-compose.yml file which is at (https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/tree/master/docker/composefiles/broker-localhost) I can configure properly the DAPS_URL and the IDENTITY_JAVAKEYSTORE
```
broker-core:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/core:latest
    container_name: broker-core
    volumes:
      - /etc/idscert/localhost:/etc/cert/
    restart: always
    environment:
    - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
    - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
    - SHACL_VALIDATION=true
    - DAPS_VALIDATE_INCOMING=true
    - IDENTITY_JAVAKEYSTORE=/etc/cert/isstbroker-keystore.jks
    - COMPONENT_URI=https://localhost/
    - COMPONENT_CATALOGURI=https://localhost/connectors/
    - JWKS_TRUSTEDHOSTS=daps.aisec.fraunhofer.de,omejdn
    - DAPS_URL=https://omejdn/token
    expose:
    - "8080"
```

When I try to obtain the description of the metadatabroker from the Dataspace Connector it gives the following error:
```
curl -X 'POST' \'https://localhost:7080/api/ids/description?recipient=https%3A%2F%2Fbroker-reverseproxy%2Finfrastructure' \-H 'accept: */*' \ -d ''

Server response
Error: response status is 417
Response body
{
  "details": {
    "reason": {
      "properties": null,
      "@id": "https://w3id.org/idsa/code/NOT_AUTHENTICATED"
    },
    "payload": "An error occurred while verifying your token",
    "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
  },
  "message": "Received unexpected response message."
}
```

Is it possible to introduce/configure in the docker-compose.yml our own daps.crt? 
This file is located at  (https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/tree/master/docker/broker-core) and I assume that this is the problem why the broker is not authenticating our local DAPS.
Waiting for your response, thanks in advance.
